### ISSUE TITLE
curl "https://mobile.proscenic.com.de/user/getEquips/$LOGINUSER"  -d "username=$LOGINUSER"

### ISSUE THREAD

**Issue by Seb6303** [andker87/Proscenic-M7-PRO#5]
Bonjour, J'ai un souci lorsque je tape la commande citée en objet ( en remplaçant LOGINUSER par le même LOGINUSER que l'étape précédente) cela me sort : 

{"code":0,"msg":"OK","data":{"content":[],"pageable":{"sort":{"sorted":false,"unsorted":true,"empty":true},"pageNumber":0,"pageSize":20,"offset":0,"paged":true,"unpaged":false},"totalElements":0,"last":true,"totalPages":0,"first":true,"sort

du coup je suis bloqué ici :( 

Si quelqu'un peux m'aider je suis preneur.

Merci beaucoup

**Comment by jayeshgarg** [comment]
Facing same issue

**Comment by jayeshgarg** [comment]
@Seb6303 were you able to solve your problem?
